---
- name: Configure DNS servers using resolvconf on Debian hosts
  hosts: servers
  become: yes
  tasks:
    - name: Install resolvconf if not installed
      apt:
        name: resolvconf
        state: present

    - name: Set DNS nameservers
      copy:
        dest: /etc/resolvconf/resolv.conf.d/head
        content: |
          nameserver 10.100.30.1
      notify:
        - reload resolvconf

  handlers:
    - name: reload resolvconf
      command: resolvconf -u

