---
- name: Update Debian Servers using apt
  hosts: servers
  become: yes
  vars:
    ansible_python_interpreter: /usr/bin/python3
  tasks:
  - name: Ensure needrestart is installed
    apt:
      name: needrestart
      state: present

  - name: Gather facts about available updates
    command: apt list --upgradable
    register: upgradable_packages

  - name: Display list of upgradable packages
    debug:
      var: upgradable_packages.stdout_lines

  - block:
    - name: Update package lists
      apt:
        update_cache: yes
        cache_valid_time: 3600
      when: upgradable_packages.stdout_lines|length > 0

    - name: Upgrade packages
      apt:
        upgrade: dist
        force: yes
      when: upgradable_packages.stdout_lines|length > 0

    - name: Restart services if required
      command: needrestart -r a

    - name: Check if a reboot is required.
      ansible.builtin.stat:
        path: /var/run/reboot-required
        get_checksum: no
      register: reboot_required_file

    - name: Reboot the server (if required).
      ansible.builtin.reboot:
      when: reboot_required_file.stat.exists == true

    - name: Remove dependencies that are no longer required.
      ansible.builtin.apt:
        autoremove: yes
